### ISSUE TITLE
Permisson error while running Pywal

### ISSUE THREAD

**Issue by SoXX-TheFennec** [dylanaraps/pywal#157]
Every time when I run Pywal this happens, the color scheme and background are set but every time I got this error.
Also (maybe it's related) when I open a new Terminal the color are back to normal.

Linux: Arch
WM: i3-gaps
Terminal: alacritty

```
image: Using image /home/soxx/Bilder/-1--Sona/-2--Artwork/BG/BG1.png
colors: Found cached colorscheme.
wallpaper: Set the new wallpaper.
colors: Set terminal colors.
export: Exported all files.
export: Exported all user files.
reload: Reloaded environment.
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==1.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 149, in main
    process_args(args)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 140, in process_args
    reload.env()
  File "/usr/lib/python3.6/site-packages/pywal/reload.py", line 88, in env
    tty()
  File "/usr/lib/python3.6/site-packages/pywal/reload.py", line 18, in tty
    subprocess.Popen([tty_script])
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/soxx/.cache/wal/colors-tty.sh'
```

ps: sorry if i use this wrong, i never used GitHub bevor

**Comment by dylanaraps** [comment]
Fixed.
