### ISSUE TITLE
theme failing to be set along with wallpaper (new alpha key)

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#164]
Hey @dylanaraps I just wanted to report this in the latest pywal version, the fix currently is to delete the theme and reload it, but I wonder if you could somehow avoid a full on error, maybe just a warning instead?

here's the error in question (older themes generated by pywal are missing the new alpha key):

```
image: Using image /home/fernando/.wallpapers/tokyo.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/wpgtk/gui/theme_picker.py", line 138, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/themer.py", line 28, in set_theme
    color.execute_gcolorchange(cs_file)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/color.py", line 244, in execute_gcolorchange
    colors = prepare_colors(image_name)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/color.py", line 213, in prepare_colors
    cdic = pywal.colors.get(image, config.WALL_DIR)
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 94, in get
    util.Color.alpha_num = colors["alpha"]
KeyError: 'alpha'
```

**Comment by dylanaraps** [comment]
Yeah, I’m aware. I haven’t pushed a new release since there’s a few bugs I
want to fix first.

Your users shouldn’t be using -git versions of pywal to begin with.

Stick to using actual tagged releases and not the latest commit I push to
master and all will be fine.

🤷‍♀️

**Comment by vKnmnn** [comment]
maybe it would help putting a version number into the cached scheme files, so they can be skipped on a mismatch

**Comment by dylanaraps** [comment]
Good idea, I’ll implement that once my laptop works again.
