### ISSUE TITLE
Redirecting stdout gives an error

### ISSUE THREAD

**Issue by m3tax** [dylanaraps/pywal#218]
When running `wal -c -i image > file`, this happens:

```
...
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==2.0.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 181, in main
    process_args(args)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 163, in process_args
    colors.palette()
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 97, in palette
    col_width = " " * (os.get_terminal_size().columns // 8)
OSError: [Errno 25] Inappropriate ioctl for device
```

Also happens if you don't use `-c`, or use a different `--backend`, but not if you redirect stderr instead of stdout.

By the way, It would also make more sense if the lines that start with `[I]` went to stdout instead of stderr.

**Comment by dylanaraps** [comment]
Fixed in https://github.com/dylanaraps/pywal/commit/b649563ebad5d7f915f038041d861d942d61a233
