### ISSUE TITLE
wal --theme

### ISSUE THREAD

**Issue by ltgouvea** [dylanaraps/pywal#224]
I'm getting this error running `wal --theme`, it was working OK a while ago. Am I missing something?
```
Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    load_entry_point('pywal==2.0.4', 'console_scripts', 'wal')()
  File "/usr/local/lib/python3.5/dist-packages/pywal/__main__.py", line 187, in main
    parse_args_exit(parser)
  File "/usr/local/lib/python3.5/dist-packages/pywal/__main__.py", line 120, in parse_args_exit
    for theme in theme.list_themes()]
  File "/usr/local/lib/python3.5/dist-packages/pywal/theme.py", line 18, in list_themes
    return [t for t in themes if os.path.isfile(t)]
  File "/usr/local/lib/python3.5/dist-packages/pywal/theme.py", line 18, in <listcomp>
    return [t for t in themes if os.path.isfile(t)]
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: argument should be string, bytes or integer, not posix.DirEntry
```

**Comment by dylanaraps** [comment]
Which version of `pywal` are you using?

**Comment by dylanaraps** [comment]
Fixed.
