### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by gigavinyl** [dylanaraps/pywal#226]
I'm trying to setup some custom templates but I seem to be running into some errors. This is the template I'm using:
```lua                              
local theme = {}

-- Default settings
theme.font = "12px scientifica"
theme.fg   = "{foreground}"
theme.bg   = "{background}"

-- Genaral colours
theme.success_fg = "{foreground}"
theme.loaded_fg  = "{background}"
theme.error_fg = "{foreground}"
theme.error_bg = "{background}"

-- Warning colours
theme.warning_fg = "{color1}"
theme.warning_bg = "{foreground}"

-- Notification colours
theme.notif_fg = "{color8}"
theme.notif_bg = "{foreground}"

-- Menu colours
theme.menu_fg                   = "{color0}"
theme.menu_bg                   = "{foreground}"
theme.menu_selected_fg          = "{foreground}"
theme.menu_selected_bg          = "{color11}"
theme.menu_title_bg             = "{foreground}"
theme.menu_primary_title_fg     = "{color9}"
theme.menu_secondary_title_fg   = "{color7}"

theme.menu_disabled_fg = "{color15}"
theme.menu_disabled_bg = theme.menu_bg
theme.menu_enabled_fg = theme.menu_fg
theme.menu_enabled_bg = theme.menu_bg
theme.menu_active_fg = "{color2}"
theme.menu_active_bg = theme.menu_bg

-- Proxy manager
theme.proxy_active_menu_fg      = '{background}'
theme.proxy_active_menu_bg      = '{foreground}'
theme.proxy_inactive_menu_fg    = '{color7}'
theme.proxy_inactive_menu_bg    = '{foreground}'

-- Statusbar specific
theme.sbar_fg         = "{foreground}"
theme.sbar_bg         = "{background}"

-- Downloadbar specific
theme.dbar_fg         = "{foreground}"
theme.dbar_bg         = "{background}"
theme.dbar_error_fg   = "{color9}"

-- Input bar specific
theme.ibar_fg           = "{background}"
theme.ibar_bg           = "{foreground}"

-- Tab label
theme.tab_fg            = "{foreground}"
theme.tab_bg            = "{background}"
theme.tab_hover_bg      = "{color8}"
theme.tab_ntheme        = "{foreground}"
theme.selected_fg       = "{color7}"
theme.selected_bg       = "{color0}"
theme.selected_ntheme   = "{color15}"
theme.loading_fg        = "{color12}"
theme.loading_bg        = "{background}"

theme.selected_private_tab_bg = "{color4}"
theme.private_tab_bg    = "{color5}"

-- Trusted/untrusted ssl colours
theme.trust_fg          = "{color10}"
theme.notrust_fg        = "{color9}"

-- General colour pairings
theme.ok = { fg = "{foreground}", bg = "{background}" }
theme.warn = { fg = "{color0}", bg = "{foreground}" }
theme.error = { fg = "{foreground}", bg = "{color9}" }

return theme

-- vim: et:sw=4:ts=8:sts=4:tw=80
```

and the error I get when I run wal is:
```
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==2.0.5', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 188, in main
    parse_args(parser)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 169, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.6/site-packages/pywal/export.py", line 63, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.6/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
IndexError: tuple index out of range
```

**Comment by dylanaraps** [comment]
You need to escape unrelated braces. You can escape them by doubling them.

Example:

```py
theme.ok = {{ fg = "{foreground}", bg = "{background}" }}
```

**Comment by gigavinyl** [comment]
Ahhh. Thanks!
