### ISSUE TITLE
Can't select themes anymore after light/dark update

### ISSUE THREAD

**Issue by metalelf0** [dylanaraps/pywal#239]
I just checked out latest master (`4af3766b15ee7d939ccd8b246d0fa317184059cb`), ran the usual `pip3 install --user .`, and now when I run `wal --themes` I get: 

```
❯ wal --theme
Traceback (most recent call last):
  File "/home/metalelf0/.local/bin/wal", line 11, in <module>
    load_entry_point('pywal==2.1.0', 'console_scripts', 'wal')()
  File "/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/__main__.py", line 193, in main
    parse_args_exit(parser)
  File "/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/__main__.py", line 124, in parse_args_exit
    theme.list_out()
  File "/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/theme.py", line 16, in list_out
    for theme in list_themes()]
  File "/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/theme.py", line 41, in list_themes
    themes = os.scandir(os.path.join(MODULE_DIR, "colorschemes", dark))
FileNotFoundError: [Errno 2] No such file or directory: '/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/colorschemes/dark'
```

I see themes in `/home/metalelf0/.local/lib/python3.6/site-packages/pywal-2.1.0-py3.6.egg/pywal/colorschemes`, but there are no `light` or `dark` subfolders.

Let me know if I can be of any help. Thank you for your great work!

**Comment by dylanaraps** [comment]
Does my latest commit fix the issue?

**Comment by metalelf0** [comment]
Yes it does! Thanks! :)

**Comment by dylanaraps** [comment]
Sorry, can you also test my newest commit? This is a greedier glob so it should fix the issue forever.

**Comment by metalelf0** [comment]
With the latest commit the issue is back.

**Comment by dylanaraps** [comment]
Reverted. :+1:
