### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by N4d4** [dylanaraps/pywal#25]
I'm trying to install pywal but i get this error
```sh
user@localtest:/tmp$ sudo pip install pywal
Collecting pywal
  Using cached pywal-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NG7xbN/pywal/setup.py", line 13
        DOWNLOAD_URL = f"https://github.com/dylanaraps/pywal/archive/{VERSION}.tar.gz"
                                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NG7xbN/pywal/
user@localtest:/tmp$ 
```

I've tried to remove the "**f**" in the DOWNLOAD_URL and now it give me this error

```
user@localtest:/tmp/pywal$ pip install .
Processing /tmp/pywal
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tdf3sz-build/setup.py", line 3, in <module>
        import pywal
      File "pywal/__init__.py", line 5, in <module>
        from pywal.settings import __version__  # noqa: F401
      File "pywal/settings.py", line 12, in <module>
        CACHE_DIR = pathlib.Path.home() / ".cache/wal/"
    AttributeError: type object 'Path' has no attribute 'home'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-tdf3sz-build/
```

OS: Debian GNU/Linux 9.0
Kernel: 4.9.0-3-amd64
Shell: bash 4.4.12

**Comment by dylanaraps** [comment]
What python version do you have installed?

```
python --version
```

**Comment by dylanaraps** [comment]
`wal` requires Python 3.6 or newer to run, based on the errors above 
I'm assuming you're on Python 3.4 or lower.

- `f strings` were added in Python 3.6.
- `Path.home` was added in Python 3.5. \[2\]

\[1\] https://www.python.org/dev/peps/pep-0498/
\[2\] https://docs.python.org/3/library/pathlib.html#pathlib.Path.home
