### ISSUE TITLE
Error message when trying to switch backends

### ISSUE THREAD

**Issue by dustvy** [dylanaraps/pywal#312]
Like the title says, every time I try to switch backends I get an error message. Just to be sure it's not user error, the command is **wal --backend colorz** (or whatever backend you want to use) right?

In case it's not user error, here is the error code I'm getting:
> Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 198, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 168, in parse_args
    wallpaper.change(colors_plain["wallpaper"])
UnboundLocalError: local variable 'colors_plain' referenced before assignment

**Comment by mpolidori** [comment]
@dylanaraps is that command meant to be run without supplying an image path? If not I have a pull request I can submit.

**Comment by KKJZ** [comment]
I am getting this error now,
```
Traceback (most recent call last):
  File "/home/user/.local/bin/wal", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pywal/__main__.py", line 231, in main
    parse_args(parser)
  File "/home/user/.local/lib/python3.8/site-packages/pywal/__main__.py", line 198, in parse_args
    wallpaper.change(colors_plain["wallpaper"])
UnboundLocalError: local variable 'colors_plain' referenced before assignment

```
Just fresh installed pywal-3.3.1

I was running `wal --backend colorz`

**Comment by KKJZ** [comment]
I am getting this error now,
```
Traceback (most recent call last):
  File "/home/user/.local/bin/wal", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pywal/__main__.py", line 231, in main
    parse_args(parser)
  File "/home/user/.local/lib/python3.8/site-packages/pywal/__main__.py", line 198, in parse_args
    wallpaper.change(colors_plain["wallpaper"])
UnboundLocalError: local variable 'colors_plain' referenced before assignment

```
Just fresh installed pywal-3.3.1

I was running wal --backend colorz

**Comment by SourabhSNath** [comment]
Same error for me
