### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Quoteme** [dylanaraps/pywal#326]
I installed pywal from the official arch-linux repository using:
`sudo pacman -S python-pywal`
but upon trying to start it, I only get the following error messages:
```
wal -i .wallpaper/redGalaxy.jpg 
[I] image: Using image redGalaxy.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 198, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 154, in parse_args
    sat=args.saturate)
  File "/usr/lib/python3.7/site-packages/pywal/colors.py", line 149, in get
    colors = getattr(backend, "get")(img, light)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 78, in get
    return adjust(colors, light)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 70, in adjust
    raw_colors[15] = util.blend_color(raw_colors[15], "#EEEEEE")
IndexError: list index out of range
```

**Comment by lasers** [comment]
@Quoteme If this issue is still happening for you, try again with your supplied imgur's image because I think imgur may be compressing the wallpaper or such... as I'm not able to reproduce this same error.

**Comment by Quoteme** [comment]
hm, I assume my image file was just corrupted.
Uploading the image to imgur and re-downloading it, solved the issue.

thanks a lot :+1:
