### ISSUE TITLE
non-hexadecimal number found in fromhex()

### ISSUE THREAD

**Issue by yousufinternet** [dylanaraps/pywal#358]
This is my first time using pywal, this is what I get when running it with a predefined theme or when loading colors from an image.

I am using arch linux, pywal version 3.2.1
```
[I] theme: Set theme to gruvbox.json.
[I] sequences: Set terminal colors.

Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.2.1', 'console_scripts', 'wal')()
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/__main__.py", line 205, in main
    parse_args(parser)
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/__main__.py", line 182, in parse_args
    export.every(colors_plain)
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/util.py", line 25, in rgb
    return "%s,%s,%s" % (*hex_to_rgb(self.hex_color),)
  File "/home/yusuf/.local/lib/python3.7/site-packages/pywal/util.py", line 116, in hex_to_rgb
    return tuple(bytes.fromhex(color.strip("#")))
ValueError: non-hexadecimal number found in fromhex() arg at position 1
```

After the error message the generated color scheme is the same every time.

**Comment by dylanaraps** [comment]
I can't reproduce this. Does the issue still occur?

**Comment by yousufinternet** [comment]
Thanks for the reply, just tried and it is working correctly if I remove the -g option which I believe generates an oomox theme.

**Comment by typkrft** [comment]
I'm actually having this same issue at the moment. It happens for me while choosing any backend. However, when I don't choose a backend it appears to run, but the theme stays the same.
I'm on Kubuntu (KDE), using Konsole with the "ln" which had been working.

**Comment by Prayag2** [comment]
Same issue. I'm getting the exact same error when trying to use different backends (I have installed the backends from PyPI).
