### ISSUE TITLE
imagemagick aborted (core dumped)

### ISSUE THREAD

**Issue by throwaway228228** [dylanaraps/pywal#365]
arch linux on kernel 4.20.0-arch1-1-ARCH
16 GiBS of ram
intel i7-7700hq
gpu hd graphics 630 & gtx 1050 ti mobile (bumblebee/nvidia 415/mesa)
ImageMagick 7.0.8-23 Q16 x86_64 2019-01-04

```
[mac@msi ~]$ wal -n -i ./Pictures/wallpapers/Cityscapes/cityscape_12.png 
[I] image: Using image cityscape_12.png.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.2.1', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 209, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 164, in parse_args
    sat=args.saturate)
  File "/usr/lib/python3.7/site-packages/pywal/colors.py", line 144, in get
    colors = getattr(backend, "get")(img, light)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 86, in get
    colors = gen_colors(img)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 41, in gen_colors
    raw_colors = imagemagick(16 + i, img, magick_command)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 19, in imagemagick
    return subprocess.check_output([*magick_command, img, *flags]).splitlines()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['magick', 'convert', '/home/mac/Pictures/wallpapers/Cityscapes/cityscape_12.png[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' died with <Signals.SIGABRT: 6>.
```

```
[mac@msi ~]$ magick convert ./Pictures/wallpapers/Cityscapes/cityscape_12.png -debug all -resize 25% -colors 6 -unique-colors txt:- 2> debug
Aborted (core dumped)
```
debug: https://gist.github.com/throwaway228228/d38f0923eb2f6ce1f456b7ab4b93120b

**Comment by dylanaraps** [comment]
Is this a pywal issue? Looks to me like its happening outside of pyal too.

**Comment by dessalines** [comment]
I'm getting this too.
