### ISSUE TITLE
wal hangs

### ISSUE THREAD

**Issue by obayit** [dylanaraps/pywal#373]
when i execute wal it hangs. here is the console output:
```
obi:~/src/intellijPywal$ wal --vte -i ~/Pictures/Wal/bg1.jpg 
[I] image: Using image bg1.jpg.
[I] theme: Set theme to _home_obi_Pictures_Wal_bg1_jpg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
^C

^CKeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/obi/.local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/home/obi/.local/lib/python3.6/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/obi/.local/lib/python3.6/site-packages/pywal/__main__.py", line 180, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/home/obi/.local/lib/python3.6/site-packages/pywal/sequences.py", line 85, in send
    util.save_file(sequences, term)
  File "/home/obi/.local/lib/python3.6/site-packages/pywal/util.py", line 84, in save_file
    file.write(data)
KeyboardInterrupt
```

**Comment by obayit** [comment]
never mind. this is probably not important
