### ISSUE TITLE
Fails on MacOS when kitty is installed

### ISSUE THREAD

**Issue by carterpayne** [dylanaraps/pywal#378]
running `wal -i "PATH" -n` on MacOS Mojave fails when kitty is installed.
pywal kitty refresh script assumes the system has `pidof` command installed which is not true for macs. installing pidof package fixes the issue.

ERROR:
```
wal -i "/wallpapers/zibIfl0.jpg" -n
[I] image: Using image zibIfl0.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] sequences: Set terminal colors.
[I] export: Exported all files.
[I] export: Exported all user files.
Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 188, in parse_args
    reload.env(tty_reload=not args.t)
  File "/usr/local/lib/python3.7/site-packages/pywal/reload.py", line 84, in env
    kitty()
  File "/usr/local/lib/python3.7/site-packages/pywal/reload.py", line 53, in kitty
    if shutil.which("kitty") and util.get_pid("kitty"):
  File "/usr/local/lib/python3.7/site-packages/pywal/util.py", line 182, in get_pid
    subprocess.check_output(["pidof", "-s", name])
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pidof': 'pidof'
```

**Comment by dylanaraps** [comment]
Fixed. `pywal` won't spill errors now. 

I've also updated the installation instructions to mention `procps-ng`. I'll also look into a more portable method of retrieving a `PID` by name.
