### ISSUE TITLE
Errors in export.py

### ISSUE THREAD

**Issue by Dersyx** [dylanaraps/pywal#380]
Hello, everyone,

I have discovered some *possible* bugs inside of the export.py script, and the util.py script. These bugs involve how pywal handles template values from the user, along with saving those values to a file, so that it can be used across the system. To fully document this, I will go through the process of what happened, and what I did to fix it (which involved hard-writing a few lines of code).

Before we continue, I would like to stress that I know the cause of the first issue (badly formatted template file), but do not know the cause of the second. It is possible the second was caused by a bad setting in my arch install, I have no idea. 

`print("Continue, please")`

The first issue to come up was with export.py, and the way that it handled template data from the user. At first, I thought that the issue was inside the code itself, not because of my bad template file. 

While executing pywal normally, I encountered the following: 

```Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: '\n    active-background'
```

At first, I thought this was because I had a bad option, or it was parsing already-compiled code inside of .Xresources. I looked deep into the code to try and find the issue. In the end, I ended up wrapping the statement in the following:

```try:
    template_data = "".join(template_data).format(**colors)
except KeyError:
    pass
```

Which did solve my problem, but definitely wasn't the most elegant of solutions.

Then, disaster struck. Another problem arose inside of util.py:

```
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 70, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 19, in template
    util.save_file(template_data, output_file)
  File "/usr/lib/python3.7/site-packages/pywal/util.py", line 84, in save_file
    file.write(data)
TypeError: write() argument must be str, not list
```

Staring at the code, I freaked. So many more issues had already arised *outside* of the pywal bugs, and now this? What the hell?

Again, in the end, I did a simple solution:

```
file.write(str(data))
```

And, again, it wasn't the prettiest. 

I had no idea why these problems had arisen, until I waited a second. I realized that export.py took in template_file, which means it was probably my fault.

Looking at the example colors-rofi-dark.rasi file on the pywal github wifi, it looks like I was off by one character.

But that's not the point of making this issue page. Pywal *should*, by default, tell the user if there is a problem in the template config file. That `try: except:` statement I added should actually do `print(Something is wrong with your template config file. Please fix the issue, and run the script again.)`. This doesn't promote the usability of this script, and should be addressed.

That only solves the export.py issue. The util.py issue, I'm assuming, was just an oversight, or possibly tied back to the export.py issue. Either way, I hope that the necessary changes are made to the code, and that my insight can help this beautiful program become more user-friendly and be used by more people.

So long, and thanks for all the fish,

Dersyx

P.S. It helps people find bugs in your code when you have comments. Just fyi.

**Comment by dylanaraps** [comment]
Can I see your template file?

**Comment by Dersyx** [comment]
Github won't let me upload the file itself, so here's the code:

```
* {
    active-background: {color2};
    active-foreground: {foreground};
    normal-background: {background};
    normal-foreground: {foreground};
    urgent-background: {color1};
    urgent-foreground: {foreground};

    alternate-active-background: {background};
    alternate-active-foreground: {foreground};
    alternate-normal-background: {background};
    alternate-normal-foreground: {foreground};
    alternate-urgent-background: {background};
    alternate-urgent-foreground: {foreground};

    selected-active-background: {color1};
    selected-active-foreground: {foreground};
    selected-normal-background: {color2};
    selected-normal-foreground: {foreground};
    selected-urgent-background: {color3};
    selected-urgent-foreground: {foreground};

    background-color: transparent;
    background: {background};
    foreground: {foreground};
    border-color: {background};
    spacing: 2;
    transparent: rgba(0,0,0,0);
    font: "xos4 Terminus";
    opacity: 90
}

#window {
    background-color: @transparent;
    border: 0;
    padding: 10px;
    transparency: "screenshot";
    color: {color1}
}

#mainbox {
    border: 0;
    padding: 0;
}

#message {
    border: 2px 0px 0px;
    border-color: @border-color;
    padding: 1px;
}

#textbox {
    text-color: {foreground};
}

#inputbar {
    children:   [ prompt,textbox-prompt-colon,entry,case-indicator ];
}

#textbox-prompt-colon {
    expand: false;
    str: ":";
    margin: 0px 0.3em 0em 0em;
    text-color: @normal-foreground;
}

#listview {
    fixed-height: 0;
    border: 2px 0px 0px;
    border-color: @border-color;
    spacing: 2px;
    scrollbar: true;
    padding: 2px 0px 0px;
}

#element {
    border: 0;
    padding: 1px;
}

#element.normal.normal {
    background-color: @normal-background;
    text-color: @normal-foreground;
}

#element.normal.urgent {
    background-color: @urgent-background;
    text-color: @urgent-foreground;
}

#element.normal.active {
    background-color: @active-background;
    text-color: @active-foreground;
}

#element.selected.normal {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
}

#element.selected.urgent {
    background-color: @selected-urgent-background;
    text-color: @selected-urgent-foreground;
}

#element.selected.active {
    background-color: @selected-active-background;
    text-color: @selected-active-foreground;
}

#element.alternate.normal {
    background-color: @alternate-normal-background;
    text-color: @alternate-normal-foreground;
}

#element.alternate.urgent {
    background-color: @alternate-urgent-background;
    text-color: @alternate-urgent-foreground;
}

#element.alternate.active {
    background-color: @alternate-active-background;
    text-color: @alternate-active-foreground;
}

#scrollbar {
    width: 4px;
    border: 0;
    handle-width: 8px;
    padding: 0;
}

#sidebar {
    border: 2px 0px 0px;
    border-color: @border-color;
}

#button {
    text-color: @normal-foreground;
}

#button.selected {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
}

#inputbar {
    spacing: 0;
    text-color: @normal-foreground;
    padding: 1px;
}

#case-indicator {
    spacing: 0;
    text-color: @normal-foreground;
}

#entry {
    spacing: 0;* {
    active-background: {color2};
    active-foreground: {foreground};
    normal-background: {background};
    normal-foreground: {foreground};
    urgent-background: {color1};
    urgent-foreground: {foreground};

    alternate-active-background: {background};
    alternate-active-foreground: {foreground};
    alternate-normal-background: {background};
    alternate-normal-foreground: {foreground};
    alternate-urgent-background: {background};
    alternate-urgent-foreground: {foreground};

    selected-active-background: {color1};
    selected-active-foreground: {foreground};
    selected-normal-background: {color2};
    selected-normal-foreground: {foreground};
    selected-urgent-background: {color3};
    selected-urgent-foreground: {foreground};

    background-color: transparent;
    background: {background};
    foreground: {foreground};
    border-color: {background};
    spacing: 2;
    transparent: rgba(0,0,0,0);
    font: "xos4 Terminus";
    opacity: 90
}

#window {
    background-color: @transparent;
    border: 0;
    padding: 10px;
    transparency: "screenshot";
    color: {color1}
}

#mainbox {
    border: 0;
    padding: 0;
}

#message {
    border: 2px 0px 0px;
    border-color: @border-color;
    padding: 1px;
}

#textbox {
    text-color: {foreground};
}

#inputbar {
    children:   [ prompt,textbox-prompt-colon,entry,case-indicator ];
}

#textbox-prompt-colon {
    expand: false;
    str: ":";
    margin: 0px 0.3em 0em 0em;
    text-color: @normal-foreground;
}

#listview {
    fixed-height: 0;
    border: 2px 0px 0px;
    border-color: @border-color;
    spacing: 2px;
    scrollbar: true;
    padding: 2px 0px 0px;
}

#element {
    border: 0;
    padding: 1px;
}

#element.normal.normal {
    background-color: @normal-background;
    text-color: @normal-foreground;
}

#element.normal.urgent {
    background-color: @urgent-background;
    text-color: @urgent-foreground;
}

#element.normal.active {
    background-color: @active-background;
    text-color: @active-foreground;
}

#element.selected.normal {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
}

#element.selected.urgent {
    background-color: @selected-urgent-background;
    text-color: @selected-urgent-foreground;
}

#element.selected.active {
    background-color: @selected-active-background;
    text-color: @selected-active-foreground;
}

#element.alternate.normal {
    background-color: @alternate-normal-background;
    text-color: @alternate-normal-foreground;
}

#element.alternate.urgent {
    background-color: @alternate-urgent-background;
    text-color: @alternate-urgent-foreground;
}

#element.alternate.active {
    background-color: @alternate-active-background;
    text-color: @alternate-active-foreground;
}

#scrollbar {
    width: 4px;
    border: 0;
    handle-width: 8px;
    padding: 0;
}

#sidebar {
    border: 2px 0px 0px;
    border-color: @border-color;
}

#button {
    text-color: @normal-foreground;
}

#button.selected {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
}

#inputbar {
    spacing: 0;
    text-color: @normal-foreground;
    padding: 1px;
}

#case-indicator {
    spacing: 0;
    text-color: @normal-foreground;
}

#entry {
    spacing: 0;
    text-color: @normal-foreground;
}

#prompt {
    spacing: 0;
    text-color: @normal-foreground;
}
    text-color: @normal-foreground;
}

#prompt {
    spacing: 0;
    text-color: @normal-foreground;
}```

I know that I copied this from somewhere (I do not remember the source, sorry), and it looks as if it would work with rofi. According to the configuration page of pywal, the first section should have two curly brackets, not just one. This could be the error. However, I don't think it would be, seeing that it says it can't index `\n    active-background`. I do see a possibility (as often happens with python) that the error is referring to the line above the one referenced.

I hope this helps,

Dersyx

**Comment by dylanaraps** [comment]
You need to escape all non-template marker curly braces `{}`. You escape them by doubling them. `{{}}`. There's an example in the user templates wiki page.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/pywal/commit/1d4127925dfe9c43281b99a43a9ef4dcf7351dc8
