### ISSUE TITLE
Issue when backend is specified

### ISSUE THREAD

**Issue by frstrikerman** [dylanaraps/pywal#383]
this issue append with every backends and with and without a json theme in cache
```bash
$ wal -b wal -i ~/Images/wallpaper/                                                                          
[I] image: Using image wallhaven-736570.jpg.
[I] theme: Set theme to _home_striker_Images_wallpaper_wallhaven-736570_jpg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                
                                

Traceback (most recent call last):
  File "/home/striker/.local/bin/wal", line 10, in <module>
    sys.exit(main())
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/util.py", line 25, in rgb
    return "%s,%s,%s" % (*hex_to_rgb(self.hex_color),)
  File "/home/striker/.local/venvs/pywal/lib/python3.6/site-packages/pywal/util.py", line 116, in hex_to_rgb
    return tuple(bytes.fromhex(color.strip("#")))
ValueError: non-hexadecimal number found in fromhex() arg at position 0
$ wal -i ~/Images/wallpaper/
[I] image: Using image wallhaven-736570.jpg.
[I] theme: Set theme to _home_striker_Images_wallpaper_wallhaven-736570_jpg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                
                                

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
```

**Comment by frstrikerman** [comment]
I forgot to mention that this issue append on both my gentoo and arch install
