### ISSUE TITLE
Traceback error when trying to use pywal

### ISSUE THREAD

**Issue by Xyverz** [dylanaraps/pywal#411]
I don't know whether this is a pywal issue or a python configuration issue, but I get the following error when I'm trying to run wal on my desktop box. (Arch)
```
[ ~ ] 36 >> wal -f "./Downloads/trillectro-aaron-campbell-2560×1080.jpg" -n
[I] theme: Set theme to trillectro-aaron-campbell-2560×1080.jpg.
Traceback (most recent call last):
  File "/home/xyverz/.local/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/home/xyverz/.local/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/xyverz/.local/lib/python3.7/site-packages/pywal/__main__.py", line 167, in parse_args
    colors_plain = theme.file(args.theme, args.l)
  File "/home/xyverz/.local/lib/python3.7/site-packages/pywal/theme.py", line 119, in file
    return parse(theme_file)
  File "/home/xyverz/.local/lib/python3.7/site-packages/pywal/theme.py", line 69, in parse
    data = util.read_file_json(theme_file)
  File "/home/xyverz/.local/lib/python3.7/site-packages/pywal/util.py", line 70, in read_file_json
    return json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
I'm not having this issue on my laptop (also Arch), and I've tried both the `python-pywal` package from the repos, and a manual install (after installing `python-pip`) after cloning the git repo. I have a feeling this has more to do with my python install or configuration, but I have no idea where to start looking.

**Comment by Xyverz** [comment]
OK, I'm stupid. I should have used `-i` instead of `-f`. Closing this issue.

**Comment by jelc53** [comment]
I am also getting this same error when I try to run ‘set theme dark —img path/to/img’. Can you provide some more detailed about your solution? 

![image](https://github.com/dylanaraps/pywal/assets/30467615/7f682166-9988-47e6-8024-706e3b7d376c)
