### ISSUE TITLE
Custom Rofi theme with template file

### ISSUE THREAD

**Issue by joeknock90** [dylanaraps/pywal#428]
Is it possible to edit the colors-rofi-dark.rasi to use a completely different theme but the colors from pywal?

For instance. I am trying to get this theme:

https://github.com/davatorium/rofi-themes/blob/master/User%20Themes/sidetab.rasi

To use rofi colors by removing the set colors and editing the file to reflect what I want it to pull from wal. 

I have also tried completely editing the colors-rofi-dark.rasi you have provided to look like this sidetab.rasi, but when regenerating wal I always get this error. 

`Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: '\n//    text-color'`

**Comment by joeknock90** [comment]
Never mind, works completely as advertised when your config VM isn't tottaly jacked up. 

Thanks!
