### ISSUE TITLE
FreeBSD freeze after wallpaper

### ISSUE THREAD

**Issue by 927589452** [dylanaraps/pywal#433]
on my `FreeBSD 12.0-RELEASE r341666 GENERIC`
a run of `wal` without the `-s` tag becomes unresponsive (killed them after several minutes and used `wal -c` to start over), while the `-s` tag allows the runs to complete.

the new color scheme is loaded only after using `(cat ~/.cache/wal/sequences &)`

different test runs
```
 wal --theme random_light  -s
[I] theme: Set theme to tempus_totus.json.
[I] sequences: Set terminal colors.
COLORS
[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[W] reload: GTK2 reload support requires Python 2.
```

```
 wal -i ~/Pictures/Wallpapers_Approved -s
[I] image: Using image NGC3324_SHO_1024.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.
COLORS
[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[W] reload: GTK2 reload support requires Python 2.
```
while without `-s` 

```
 wal -i ~/Pictures/Wallpapers_Approved
[I] image: Using image Cl6pvBH.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 16
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
^C^CKeyboardInterrupt

During handling of the above exception, another exception
occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/wal", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/venvs/pywal/lib/python3.6/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/user/.local/venvs/pywal/lib/python3.6/site-packages/pywal/__main__.py", line 180, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/home/user/.local/venvs/pywal/lib/python3.6/site-packages/pywal/sequences.py", line 85, in send
    util.save_file(sequences, term)
  File "/home/user/.local/venvs/pywal/lib/python3.6/site-packages/pywal/util.py", line 84, in save_file
    file.write(data)
KeyboardInterrupt
```

**Comment by 927589452** [comment]
The problem turned out to be a dead pts
the current version seems to be mostly fixed and catching errors
maybe even except device is not configured?

**Comment by golam71** [comment]
i am on archlinux but restart fixed it
