### ISSUE TITLE
Unable to generate colorscheme

### ISSUE THREAD

**Issue by AcroBanwagon** [dylanaraps/pywal#437]
Either using wal -R, or wal -i results in the same error.

Distro - ArchLinux
python version - 3.7.4
pywal version - 3.3.0

wal -i output:
```
[I] image: Using image wallpaper.
[I] theme: Set theme to _home_acro__config_wallpaper_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

<Colors>

Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
ValueError: unexpected '{' in field name
```

**Comment by dylanaraps** [comment]
There seems to be in issue in one of your templates. Are you using any custom templates?

**Comment by AcroBanwagon** [comment]
Yeah, I'm using one for dunst.

https://pastebin.com/GWYL2qHF

Now that you mentioned the templates, I'm going to assume it's my vim fold markers that are causing the issue.

**Comment by dylanaraps** [comment]
>  I'm going to assume it's my vim fold markers that are causing the issue.
Yup!
