### ISSUE TITLE
Call not ending, must quit with CTRL+C

### ISSUE THREAD

**Issue by ThibaultNocchi** [dylanaraps/pywal#461]
Hello,

When I am calling a basic command, `wal -i Pictures/`, it works as expected but it doesn't eventually return.

I get the usual command output:
```
[I] image: Using image B3FeWQS.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
```

But I must use twice CTRL+C to quit, and then I get the Python error output and it ends.
```
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thibault/.local/bin/wal", line 10, in <module>
    sys.exit(main())
  File "/home/thibault/.local/lib/python3.7/site-packages/pywal/__main__.py", line 223, in main
    parse_args(parser)
  File "/home/thibault/.local/lib/python3.7/site-packages/pywal/__main__.py", line 195, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/home/thibault/.local/lib/python3.7/site-packages/pywal/sequences.py", line 85, in send
    util.save_file(sequences, term)
  File "/home/thibault/.local/lib/python3.7/site-packages/pywal/util.py", line 86, in save_file
    file.write(data)
KeyboardInterrupt
```

What can be done to stop it hanging? I am using the latest version from Git. Thanks!

**Comment by ThibaultNocchi** [comment]
I'm sorry, after a reboot it works. I also had a problem with new terminals not getting the current theme, but it also fixed it. I'm sorry, have a nice day.
