### ISSUE TITLE
No working after upgrade

### ISSUE THREAD

**Issue by annata83** [dylanaraps/pywal#470]
```
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.8/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.8/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.8/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: 'colour5'
```
-
OS- Arch
Pywal- 3.3.0

**Comment by suvernev-d** [comment]
Might be the same as #408.

Maybe some custom template in `~/.config/wal/templates` is messing with pywal?

**Comment by annata83** [comment]
yep, That was It. Thanks
