### ISSUE TITLE
Using pywal as a module fails

### ISSUE THREAD

**Issue by fufexan** [dylanaraps/pywal#471]
I have the script mentioned as the simple example in the [Using pywal as a module](https://github.com/dylanaraps/pywal/wiki/Using-%60pywal%60-as-a-module#simple-example) page. It's been working really well for the past 6 months, but recently started to pose problems. The most noticeable one is not setting the wallpaper, but changing the terminal colours for open terminals only. Reinstalling both pywal and python yielded no solution. The output of running the script is:
```
Traceback (most recent call last):
  File "/home/mihai/bin/wal.py", line 41, in <module>
    main()
  File "/home/mihai/bin/wal.py", line 20, in main
    pywal.sequences.send(colors, False)
  File "/usr/lib/python3.6/site-packages/pywal/sequences.py", line 87, in send
    util.save_file(sequences, os.path.join(cache_dir, "sequences"))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool
```

The thing is, when using the `wal` command (`/usr/bin/wal`), everything works and there are no errors.

**OS**: Void Linux
**pywal** version: 3.3.0
**python** version: 3.6.9

If anyone needs the script:
```
#!/usr/bin/python
"""Simple script for wal api."""
import pywal


def main():
    """Main function."""
    # Validate image and pick a random image if a
    # directory is given below.
    image = pywal.image.get("/home/mihai/.config/wallpapers/")

    # Return a dict with the palette.
    # Set quiet to 'True' to disable notifications.
    colors = pywal.colors.get(image)

    # Apply the palette to all open terminals.
    # Second argument is a boolean for VTE terminals.
    # Set it to true if the terminal you're using is
    # VTE based. (xfce4-terminal, termite, gnome-terminal.)
    pywal.sequences.send(colors, False)

    # Export all template files.
    pywal.export.every(colors, cache_dir)

    # Export individual template files.
    pywal.export.color(colors, "xresources", "/home/mihai/.Xresources")
    pywal.export.color(colors, "shell", "/home/mihai/colors.sh")

    # Reload xrdb, i3 and polybar.
    pywal.reload.env()

    # Reload individual programs.
    pywal.reload.i3()
    pywal.reload.polybar()
    pywal.reload.xrdb()

    # Set the wallpaper.
    pywal.wallpaper.change(image)


main()
```

**Comment by jimbob88** [comment]
The issue is the fact in the new versions of pywal, the send function looks like so:
```python
def send(colors, cache_dir=CACHE_DIR, to_send=True, vte_fix=False):
```
This means one has to change:
```python
pywal.sequences.send(colors, False)
```
To:
```python
pywal.sequences.send(colors, vte_fix=False)
```

I think it should be also noted that the latest copy of the Wiki documentation has not been updated to include this and reads:
```python
pywal.sequences.send(colors, vte=False)
```
instead of:
```python
pywal.sequences.send(colors, vte_fix=False)
```

**Comment by dylanaraps** [comment]
I've updated the Wiki documentation, thanks for the heads up. :+1:
