### ISSUE TITLE
Error message on Ubuntu 19.10

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/pywal#489]
All the sudden I'm getting this error message when I run pywal, although the app is still working correctly.

```
Traceback (most recent call last):
  File "/usr/local/bin/wal", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/local/lib/python3.7/dist-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/usr/local/lib/python3.7/dist-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/local/lib/python3.7/dist-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: 'width'
```
Any help would be appreciated. I tried reinstlling through pip3 already. No dice.
Thanks.

**Comment by dylanaraps** [comment]
That's an error in one of your templates it looks like. If you have no templates, it's an error in one of pywal's templates though doubtful.

**Comment by vaskark** [comment]
Many thanks. That was it. I was messing around trying to get a dunst template working.
