### ISSUE TITLE
Bug from pre-pywall seems back

### ISSUE THREAD

**Issue by rawzone** [dylanaraps/pywal#49]
Seems like [this bug](https://github.com/dylanaraps/wal/issues/31) or related is back. When trying to start Dwarf Fortress I get the following:

```
19:17:37 user@host LinuxLNP-0.43.05-r05 ./startlnp 
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/username/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 119, in __init__
  File "/home/username/df/python_lnp/build/lnp/out00-PYZ.pyz/core.lnp", line 212, in initialize_ui
  File "/home/username/df/python_lnp/build/lnp/out00-PYZ.pyz/tkgui.tkgui", line 131, in __init__
  File "/home/username/df/python_lnp/build/lnp/out00-PYZ.pyz/Tkinter", line 1810, in __init__
_tkinter.TclError: bad cursor spec "#E0E0DF"
[WARNING] startlnp: Failed to start PyLNP
```

**Comment by dylanaraps** [comment]
Try the latest master.

Once you do a `git clone` you can run it from the repo with `python -m pywal -i /path/to/img.jpg`.

**Comment by tkamat** [comment]
A fellow dwarf fortress player using pywal! Great minds think alike :p

**Comment by dylanaraps** [comment]
Ping @rawzone

**Comment by dylanaraps** [comment]
Should be fixed now, reopen if it still occurs.
