### ISSUE TITLE
Error on FreeBSD

### ISSUE THREAD

**Issue by plasmoduck** [dylanaraps/pywal#517]
Wal as been working fine, then all of a sudden I get this:

[I] wallpaper: Set the new wallpaper.
Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 180, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/usr/local/lib/python3.7/site-packages/pywal/sequences.py", line 85, in send
    util.save_file(sequences, term)
  File "/usr/local/lib/python3.7/site-packages/pywal/util.py", line 83, in save_file
    with open(export_file, "w") as file:
OSError: [Errno 6] Device not configured: '/dev/pts/1'

**Comment by dylanaraps** [comment]
This is related to your system and there's nothing I can do to fix it on my side. It's likely that a reboot will fix this. Thanks for opening this issue.
