### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by plasmoduck** [dylanaraps/pywal#519]
This never used to happen, but has been happening everytime I run wal lately. How to fix? FreeBSD

Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')()
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/local/lib/python3.7/site-packages/pywal/__main__.py", line 188, in parse_args
    reload.env(tty_reload=not args.t)
  File "/usr/local/lib/python3.7/site-packages/pywal/reload.py", line 84, in env
    kitty()
  File "/usr/local/lib/python3.7/site-packages/pywal/reload.py", line 53, in kitty
    if shutil.which("kitty") and util.get_pid("kitty"):
  File "/usr/local/lib/python3.7/site-packages/pywal/util.py", line 182, in get_pid
    subprocess.check_output(["pidof", "-s", name])
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pidof': 'pidof'

**Comment by dylanaraps** [comment]
The `pidof` command is missing. We can probably remove its usage.
