### ISSUE TITLE
No decode deligate

### ISSUE THREAD

**Issue by mrq-andras** [dylanaraps/pywal#547]
Hi! i'm new to ubuntu and have been using ubuntu 20.04, with i3 on zsh. I use the gnome terminal. It'sworked perfectly fine up until about a week ago, I have zero clue what could have gone wrong, anyone have any ideas? This is the output i get whenever
I try to run the 'wal -i' command.
                                                                                                      
[I] image: Using image hotline-miami.jpeg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
convert: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/562.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3285.
Traceback (most recent call last):
  File "/home/andras/.local/bin//wal", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/local/lib/python3.8/dist-packages/pywal/__main__.py", line 163, in parse_args
    colors_plain = colors.get(image_file, args.l, args.backend,
  File "/usr/local/lib/python3.8/dist-packages/pywal/colors.py", line 144, in get
    colors = getattr(backend, "get")(img, light)
  File "/usr/local/lib/python3.8/dist-packages/pywal/backends/wal.py", line 86, in get
    colors = gen_colors(img)
  File "/usr/local/lib/python3.8/dist-packages/pywal/backends/wal.py", line 41, in gen_colors
    raw_colors = imagemagick(16 + i, img, magick_command)
  File "/usr/local/lib/python3.8/dist-packages/pywal/backends/wal.py", line 19, in imagemagick
    return subprocess.check_output([*magick_command, img, *flags]).splitlines()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['magick', 'convert', '/home/andras/pictures/Wallpapers/hotline-miami.jpeg[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

**Comment by Bappamaiti** [comment]
I am on windows 10 64bit PC.

Below is the similar kind of issue I am facing.
![image](https://user-images.githubusercontent.com/81735229/114698657-fb9e8280-9d3c-11eb-9c98-12df448fd907.png)
