### ISSUE TITLE
Hangs on writing the file

### ISSUE THREAD

**Issue by AMTitan** [dylanaraps/pywal#616]
I have used this in the past and it has worked but for some reason, it hangs. (I have waited for 1hr to see if it does anything and nope.) What I have observed is that it does everything but save the file (as you can see from the dump) I have no idea why it can but I hope I can. What I get back is
```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/usr/lib/python3.9/site-packages/pywal/__main__.py", line 180, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/usr/lib/python3.9/site-packages/pywal/sequences.py", line 85, in send
    util.save_file(sequences, term)
  File "/usr/lib/python3.9/site-packages/pywal/util.py", line 84, in save_file
    file.write(data)
```
I hope this helps.

**Comment by AMTitan** [comment]
Sorry I saw that you already fixed it you just did not update the pip install way (not with git).

**Comment by AMTitan** [comment]
but even with the new version it still hangs tho

**Comment by AMTitan** [comment]
so I did find out that restarting my computer did fix it
