### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by sleepntsheep** [dylanaraps/pywal#650]
➜  ~ wal -i Pictures/wall.jpg
[I] image: Using image wall.jpg.
[I] theme: Set theme to _home_sheep_Pictures_wall_jpg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                
                                

Traceback (most recent call last):
  File "/usr/bin/wal", line 33, in <module>
    sys.exit(load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')())
  File "/home/sheep/.local/lib/python3.10/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/sheep/.local/lib/python3.10/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/home/sheep/.local/lib/python3.10/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/home/sheep/.local/lib/python3.10/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
AttributeError: 'Color' object has no attribute 'alpha_dec'. Did you mean: 'alpha_num'?

**Comment by UtkarshVerma** [comment]
I am also getting this for `{background.red}`. Do we have a fix for this?

**Comment by RandomExplosion** [comment]
> I am also getting this for `{background.red}`. Do we have a fix for this?

I'm getting the same here lol

**Comment by RandomExplosion** [comment]
The source and docs both suggest that this should work.

**Comment by scrwww** [comment]
It seems that adding `alpha_dec = "100"` inside the Color class in util.py works for solving this issue.
The alpha_dec format is missing from util.py
