### ISSUE TITLE
pywal broken on Arch update

### ISSUE THREAD

**Issue by gianmarcogg03** [dylanaraps/pywal#653]
I have Arch Linux on the zen kernel 5.15.7 and after a full system upgrade pywal broke and gives this error every time I try running it.
```
Traceback (most recent call last):
  File "/usr/bin/wal", line 33, in <module>
    sys.exit(load_entry_point('pywal==3.3.1', 'console_scripts', 'wal')())
  File "/usr/bin/wal", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywal
```

**Comment by kylosus** [comment]
Did you get pywal from AUR? If so, you need to rebuild/reinstall it (and other AUR python packages) after the 3.10 update.

Also see:
https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/

**Comment by gianmarcogg03** [comment]
That solved it, thanks.
