### ISSUE TITLE
Error "template_data = "".join(template_data).format(**colors)"

### ISSUE THREAD

**Issue by aryneko** [dylanaraps/pywal#659]
```
Traceback (most recent call last):
  File "/home/ariel/.local/bin/wal", line 33, in <module>
    sys.exit(load_entry_point('pywal==3.3.0', 'console_scripts', 'wal')())
  File "/home/ariel/.local/lib/python3.10/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/ariel/.local/lib/python3.10/site-packages/pywal/__main__.py", line 185, in parse_args
    export.every(colors_plain)
  File "/home/ariel/.local/lib/python3.10/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/home/ariel/.local/lib/python3.10/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
ValueError: unexpected '{' in field name
```

pywal version
wal 3.3.0

**Comment by k3nden** [comment]
I resolved this error by removing any templates in the template directory (.config/wal/templates.)
