### ISSUE TITLE
No such file or directory: '/dev/pts/' on Mac

### ISSUE THREAD

**Issue by aeikenberry** [dylanaraps/pywal#67]
OS: macOS Sierra 10.12.5

Just installed with pip3, and am seeing this:

```
~ » sudo pip3 install pywal
Collecting pywal
Installing collected packages: pywal
Successfully installed pywal-0.5.7
```

```
~ » wal -i ~/Dropbox/Wallpapers/RdpGQ6o.jpg
image: Using image /Users/aaron/Dropbox/Wallpapers/RdpGQ6o.jpg
colors: Found cached colorscheme.
Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pywal/__main__.py", line 126, in main
    process_args(args)
  File "/usr/local/lib/python3.6/site-packages/pywal/__main__.py", line 111, in process_args
    sequences.send(colors_plain, args.t)
  File "/usr/local/lib/python3.6/site-packages/pywal/sequences.py", line 48, in send
    terminals = [f"/dev/pts/{term}" for term in os.listdir("/dev/pts/")
FileNotFoundError: [Errno 2] No such file or directory: '/dev/pts/'
```

I'm able to run `python3 -m pywal -i ~/Dropbox/Wallpapers/RdpGQ6o.jpg` just fine though on the pywal-0.5.7 master branch.

**Comment by dylanaraps** [comment]
I haven't released a new version yet, I'm waiting on #66 before I do. The version you installed doesn't include macOS support.

**Comment by aeikenberry** [comment]
Yep, sorry. just saw i was looking at old code :/ oops.

**Comment by dylanaraps** [comment]
All good, no worries.
