### ISSUE TITLE
Pywal Error in Version: "wal 3.3.0"

### ISSUE THREAD

**Issue by ghost** [dylanaraps/pywal#679]
## Pywal Version:

3.3.0

<hr>

## Tried:  

- Restarting the System
- Reinstalling pywal
- Clean pywal cache
- Tried fixing the code
- Tried other backends (all of them but still same error occurs)
- Tried other wallpapers with different formats

<hr>

## System:

```
⮞ neofetch
    _,--._.-,           ┌───────── Hardware Information ─────────┐
   /\_r-,\_ )           ​ ​     BOD-WXX9 M1010
.-.) _;='_/ (.;         ​ ​     11th Gen Intel i5-1135G7 (8) @ 2.4GHz
 \ \'     \/S )         ​ ​ ﬙    Intel TigerLake-LP GT2 [Iris Xe Graphics]
  L.'-. _.'|-'          ​ ​  (/)   42G / 461G (10%)
 <_`-'\'_.'/            ​ ​     3068MiB / 15801MiB (19%)
   `'-._( \             ​ ​     1920x1080 @ 60.03Hz
    ___   \,      ___   ​ ​  1   42% [Discharging]
    \ .'-. \   .-'_. /  ├───────── Software Information ─────────┤
     '._' '.\/.-'_.'    ​ ​     Pop!_OS 22.04 LTS x86_64
        '--``\('--'     ​ ​     bash 5.1.16
              \         ​ ​     alacritty
              `\,       ​ ​     Orchis-Dark
                \|      ​ ​     Pop
                        ​ ​     2758 (dpkg), 10 (snap)
                        ​ ​     8 hours, 51 mins
                        └───────────────────────────────────────┘
                                                  
```
<hr> 

## Error Code:  
```
⮞ wal -i wallpaper.jpg
[I] image: Using image wallpaper.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
convert convert: Unrecognized option (-unique-colors).
Traceback (most recent call last):
  File "/home/deidalos/.local/bin/wal", line 8, in <module>
    sys.exit(main())
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/__main__.py", line 163, in parse_args
    colors_plain = colors.get(image_file, args.l, args.backend,
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/colors.py", line 144, in get
    colors = getattr(backend, "get")(img, light)
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/backends/wal.py", line 86, in get
    colors = gen_colors(img)
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/backends/wal.py", line 41, in gen_colors
    raw_colors = imagemagick(16 + i, img, magick_command)
  File "/home/deidalos/.local/lib/python3.10/site-packages/pywal/backends/wal.py", line 19, in imagemagick
    return subprocess.check_output([*magick_command, img, *flags]).splitlines()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['convert', '/home/deidalos/Pictures/wallpaper/wallpaper.jpg[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.```

**Comment by robwaz** [comment]
It looks like the `convert` command on your system does not support the `-unique-colors` flag.

Are your packages up to date?

`sudo apt update`
`sudo apt upgrade`
`sudo apt install imagemagick`

**Comment by Dreded** [comment]
just ran into this same issue,
openSUSE tumbleweed

subprocess.CalledProcessError: Command '['magick', 'convert', '/home/user/Pictures/wallpapers/Lofi-Room.png[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

its the txt:- bit it has an issue with, running with a filename there works fine

**Comment by Dreded** [comment]
Figured it out, in image Magick 7 you are no longer allowed to write to stdout by default

Had to go into /etc/ImageMagick-7/policy.xml and change the policy for '-' from 'none' to 'write'
