### ISSUE TITLE
Stuck after set the new wallpaper

### ISSUE THREAD

**Issue by albert-ying** [dylanaraps/pywal#680]
```
wal -i "$WALLPAPER"
[I] image: Using image 5x8rn8uaetf81-nord.png.
[I] theme: Set theme to _Users_A_Y_OneDrive - Harvard University_Wallpaper_favorite_5x8rn8uaetf81-nord_png_16_dark_None_None_68120_1.1.0.json.
[I] colors: Found cached colorscheme.
17
[I] wallpaper: Set the new wallpaper.
```
Then it stuck here forever, I had to hit `ctrl-c` to terminate it

```
^C^CKeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/A.Y/miniconda3/bin/wal", line 8, in <module>
    sys.exit(main())
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/pywal/__main__.py", line 234, in main
    parse_args(parser)
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/pywal/__main__.py", line 206, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/pywal/sequences.py", line 86, in send
    util.save_file(sequences, term)
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/pywal/util.py", line 132, in save_file
    file.write(data)
KeyboardInterrupt

```

**Comment by albert-ying** [comment]
It works after I comment out here ("pywal/sequences.py", line 86)

```
def send(colors, cache_dir=CACHE_DIR, to_send=True, vte_fix=False):
    """Send colors to all open terminals."""
    if OS == "Darwin":
        tty_pattern = "/dev/ttys00[0-9]*"

    else:
        tty_pattern = "/dev/pts/[0-9]*"

    sequences = create_sequences(colors, vte_fix)

    # Writing to "/dev/pts/[0-9] lets you send data to open terminals.
    # if to_send:
    #     for term in glob.glob(tty_pattern):
    #         util.save_file(sequences, term)

    util.save_file(sequences, os.path.join(cache_dir, "sequences"))
    logging.info("Set terminal colors.")
```

Still not sure why tho -- and this disabled the update to open terminal

**Comment by albert-ying** [comment]
Resolved after restart...
