### ISSUE TITLE
[MacOs] error: subprocess-exited-with-error, error: metadata-generation-failed, during pip installation.

### ISSUE THREAD

**Issue by aravezskinteeth** [dylanaraps/pywal#691]
Intel Macos 11.4 BigSur, Python 3.10.2

During installation with pip3 i get these two errors: 

error: subprocess-exited-with-error and Encountered error while generating package metadata.

```shell 
$ pip3 install pywal
Collecting pywal
  Downloading pywal-3.3.0.tar.gz (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1k/10m5nnwd177fg2zsy6tpfhc00000gn/T/pip-install-xdb8gpaf/pywal_9bf1cb86e5014060926e244f3f8da9de/setup.py", line 14, in <module>
          setuptools.setup(
      AttributeError: module 'setuptools' has no attribute 'setup'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```

I already tried to install by cloning the repo first too, but i get the same output.

**Comment by aravezskinteeth** [comment]
Found out that setup tools needed to update. Corrected the issue with `sudo pip3 install --upgrade setuptools`. [Reference](https://github.com/GoSecure/pyrdp/issues/65).
