### ISSUE TITLE
pathlib seems to have broken, help?

### ISSUE THREAD

**Issue by keyuq** [dylanaraps/pywal#83]
`
Traceback (most recent call last):
File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==0.5.11', 'console_scripts', 'wal')()
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python3.6/site-packages/pywal/__init__.py", line 12, in <module>
    from .settings import __version__
File "/usr/lib/python3.6/site-packages/pywal/settings.py", line 19, in <module>
    HOME = pathlib.Path.home()
AttributeError: type object 'Path' has no attribute 'home'
`

I cloned and used https://github.com/ritiek/spotify-downloader. Immediately after, every time I open a terminal it spits out the above error. You can fix it by reinstalling pywal, but I'm curious as to why it breaks. Any ideas?

**Comment by linuxunil** [comment]
Update your pywal.  Pathlib was removed a few days ago.
