### ISSUE TITLE
Error with pywal 0.2.1

### ISSUE THREAD

**Issue by MannaHoc** [dylanaraps/pywal#9]
Hi, sorry to bother you (and for my bad english)

I just installed the latest version using `pip install pywal` but when I run `wal ...` I have the following error :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2299, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pywal' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    load_entry_point('pywal==0.2.1', 'console_scripts', 'wal')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: module 'pywal' has no attribute 'main'

```
OS : Debian (Stretch) / Python : 3.6
Previous version (before pywal was split in several files) worked fine.
I don't know what information you may need so I will try to provide everything you ask for.

**Comment by Clyybber** [comment]
Can confirm.

**Comment by danielx** [comment]
You can downgrade to the previous version until this gets fixed. A new release will have to be published to fix this issue.

```bash
pip install -I pywal==0.1.6
```

**Comment by Clyybber** [comment]
How long will a release take?

**Comment by dylanaraps** [comment]
I've released `0.2.2`, thanks guys. :)

**Comment by dylanaraps** [comment]
Actually, this just broke `pywal` for me.

```sh
dylan ~ >sudo pip install pywal
[sudo] password for dylan: 
Collecting pywal
  Downloading pywal-0.2.2.tar.gz
Building wheels for collected packages: pywal
  Running setup.py bdist_wheel for pywal ... done
  Stored in directory: /root/.cache/pip/wheels/0b/ef/19/d2568793bc194afaa0f5202dfb62370c0594fe99f67484d26e
Successfully built pywal
Installing collected packages: pywal
Successfully installed pywal-0.2.2
dylan ~ >wal
Traceback (most recent call last):
  File "/usr/bin/wal", line 7, in <module>
    from pywal.__main__ import main
ModuleNotFoundError: No module named 'pywal.__main__'
dylan ~ >wal
Traceback (most recent call last):
  File "/usr/bin/wal", line 7, in <module>
    from pywal.__main__ import main
ModuleNotFoundError: No module named 'pywal.__main__'
```

**Comment by dylanaraps** [comment]
Fixed.

**Comment by dylanaraps** [comment]
Ok, it turns out there was still an old cached `pyc` version of `wal` in my `.local` folder which was breaking my pip install.
